### ISSUE TITLE
android 6 users crash

### ISSUE THREAD

**Issue by MKelman** [TapResearch/TapResearch-Android-SDK#12]
version: 2.4.1

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adfone.lycarewards.staging, PID: 4334
    java.lang.RuntimeException: Unable to create application com.play2pay.app.LycaApp: java.lang.NullPointerException: Attempt to invoke virtual method 'com.tapr.c.e.e com.tapr.b.b.b.b()' on a null object reference

**Comment by philip-tap** [comment]
This issue is closed as 2.4.1 is no longer support. As for Android 6 users we have not supported that OS since 2.3 range SDKs.
