### ISSUE TITLE
Cant Find create App Option

### ISSUE THREAD

**Issue by m-anshuman2166** [TapResearch/TapResearch-Android-SDK#7]
![image](https://user-images.githubusercontent.com/72782632/134898140-c4c7c29f-2e23-4ee3-b3d8-ca4110b0d0d5.png)
I cant find Create App Option 
:(

**Comment by psymike** [comment]
When you create an account, you'll need to select the Publisher / Developer option
<img width="978" alt="image" src="https://user-images.githubusercontent.com/1207453/208160516-077e4144-4ac9-46a5-83f9-831e02227b51.png">
